# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://modmuss50.me/fabric.html
	minecraft_version=26.2
	loader_version=0.19.3
	loom_version=1.17-SNAPSHOT

# Mod Properties
	mod_version = 2.0.0
	maven_group = de.jakobkruse
	archives_base_name = tikfinity

# Dependencies
	# check this on https://modmuss50.me/fabric.html
	fabric_version=0.154.2+26.2
	cloth_config_version=26.2.155
	modmenu_version=20.0.1
